# Generated by Django 3.2.6 on 2021-10-20 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(default='asss', upload_to='pythend'),
            preserve_default=False,
        ),
    ]
